import 'package:bombay_chowpati/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.signUp: "Sign Up",
  AppStrings.areYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  AppStrings.no: "No",
  AppStrings.yesExit: "Yes, exit",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.hello: "Hello ",
  AppStrings.noDataFound: "No data found",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "Log Out",
  AppStrings.enterEmailPhoneNumber: "Enter email / phone number",
  AppStrings.pleaseEnterEmailPhoneNumber: "Please enter email / phone number",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password",
  AppStrings.createOrder: "Create Order",
  AppStrings.quantity: "Quantity",
  AppStrings.enterQuantity: "Enter quantity",
  AppStrings.pleaseEnterQuantity: "Please enter quantity",
  AppStrings.orderDetails: "Order Details",
  AppStrings.add: "Add",
  AppStrings.invalidInputs: "Invalid inputs",
  AppStrings.selectOrCaptureAImage: "Select or Capture a Image",
  AppStrings.select: "Select",
  AppStrings.camera: "Camera",
  AppStrings.gallery: "Gallery",
  AppStrings.remove: "Remove",
  AppStrings.successfullyDownloadedAtDownloadFolder: "Successfully downloaded at 'Download' folder.",
  AppStrings.downloadFailedPleaseTryAgain: "Download failed, Please try again.",
  AppStrings.contact: "Contact",
  AppStrings.contactNumber: "Contact Number",
  AppStrings.enterContactNumber: "Enter contact number",
  AppStrings.pleaseEnterContactNumber: "Please enter contact number",
  AppStrings.edit: "Edit",
  AppStrings.cancel: "Cancel",
  AppStrings.delete: "Delete",
  AppStrings.update: 'Update',
  AppStrings.newVersionAvailable: 'A new version is available. Please upgrade to it.',
  AppStrings.orderDate: 'Order date',
  AppStrings.welcomePageTitleOne: 'VANILLA CHOCOLATE HONEY WITH THE CHERRY ON TOP',
  AppStrings.welcomePageSubtitleOneTwo: 'It\'s summer time',
  AppStrings.welcomePageTitleTwo: 'ENJOY YOUR FAVOURITE ICE CREAM FLAVOUR',
  AppStrings.welcomePageTitleThree: 'A FLAVOUR THAT FITS YOUR SPECIAL DAY',
  AppStrings.welcomePageSubtitleThree: 'Come and chase me',
  AppStrings.forgotPassword: 'Forgot password?',
  AppStrings.or: 'Or',
  AppStrings.enterYourEmailAddress: 'Enter your email address',
  AppStrings.pleaseEnterYourEmailAddress: 'Please enter your email address',
  AppStrings.invalidEmailAddress: 'Invalid email address',
  AppStrings.weWillSendYouAMessageToSetOrResetYourNewPassword: 'We will send you a message to set or reset your new password',
  AppStrings.sendCode: 'Send code',
  AppStrings.pleaseEnterCode: 'Please enter code',
  AppStrings.invalidCode: 'Invalid code',
  AppStrings.resend: 'Resend',
  AppStrings.reset: 'Reset',
  AppStrings.confirm: 'Confirm',
};
