import 'package:bombay_chowpati/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.signUp: "સાઇન અપ કરો",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "લૉગ આઉટ",
  AppStrings.enterEmailPhoneNumber: "ઈમેલ/ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterEmailPhoneNumber: "કૃપા કરીને ઇમેઇલ / ફોન નંબર દાખલ કરો",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો",
  AppStrings.passwordMustContain: "પાસવર્ડમાં ઓછામાં ઓછો એક લોઅરકેસ લેટર, અપરકેસ લેટર, નંબર અને સ્પેશિયલ કેરેક્ટર ન્યૂનતમ લંબાઈ 8 હોવી જોઈએ.",
  AppStrings.createOrder: "ઓર્ડર ઉમેરો",
  AppStrings.quantity: "જથ્થો",
  AppStrings.enterQuantity: "જથ્થો દાખલ કરો",
  AppStrings.pleaseEnterQuantity: "કૃપા કરીને જથ્થો દાખલ કરો",
  AppStrings.orderDetails: "ઓર્ડરની વિગતો",
  AppStrings.add: "ઉમેરો",
  AppStrings.invalidInputs: "અમાન્ય ઇનપુટ્સ",
  AppStrings.selectOrCaptureAImage: "છબી પસંદ કરો અથવા કેપ્ચર કરો",
  AppStrings.select: "પસંદ કરો",
  AppStrings.camera: "કેમેરા",
  AppStrings.gallery: "ગેલેરી",
  AppStrings.remove: "નાપસંદ કરો",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' ફોલ્ડર પર સફળતાપૂર્વક ડાઉનલોડ કર્યું.",
  AppStrings.downloadFailedPleaseTryAgain: "ડાઉનલોડ નિષ્ફળ થયું, કૃપા કરીને ફરી પ્રયાસ કરો.",
  AppStrings.contact: "સંપર્ક",
  AppStrings.contactNumber: "સંપર્ક નંબર",
  AppStrings.enterContactNumber: "સંપર્ક નંબર દાખલ કરો",
  AppStrings.pleaseEnterContactNumber: "કૃપા કરીને સંપર્ક નંબર દાખલ કરો",
  AppStrings.edit: "સંપાદિત કરો",
  AppStrings.cancel: "રદ કરો",
  AppStrings.delete: "કાઢી નાખો",
  AppStrings.update: 'અપડેટ કરો',
  AppStrings.newVersionAvailable: 'નવું સંસ્કરણ ઉપલબ્ધ છે. કૃપા કરીને તેમાં અપગ્રેડ કરો.',
  AppStrings.orderDate: 'ઓર્ડર તારીખ',
  AppStrings.welcomePageTitleOne: 'ટોચ પર ચેરી સાથે વેનીલા ચોકલેટ મધ',
  AppStrings.welcomePageSubtitleOneTwo: 'ઉનાળાનો સમય છે',
  AppStrings.welcomePageTitleTwo: 'તમારા મનપસંદ આઈસક્રીમ ફ્લેવરનો આનંદ લો',
  AppStrings.welcomePageTitleThree: 'એક સ્વાદ જે તમારા ખાસ દિવસને અનુરૂપ છે',
  AppStrings.welcomePageSubtitleThree: 'આવો અને મારો પીછો કરો',
  AppStrings.forgotPassword: 'પાસવર્ડ ભૂલી ગયા છો?',
  AppStrings.or: 'અથવા',
  AppStrings.enterYourEmailAddress: 'તમારુ ઇમેઇલ એડ્રેસ દાખલ કરો',
  AppStrings.pleaseEnterYourEmailAddress: 'કૃપા કરીને તમારું ઇમેઇલ એડ્રેસ દાખલ કરો',
  AppStrings.invalidEmailAddress: 'અમાન્ય ઇમેઇલ એડ્રેસ',
  AppStrings.weWillSendYouAMessageToSetOrResetYourNewPassword: 'અમે તમને તમારો નવો પાસવર્ડ સેટ કરવા અથવા રીસેટ કરવા માટે એક સંદેશ મોકલીશું',
  AppStrings.sendCode: 'કોડ મોકલો',
  AppStrings.pleaseEnterCode: 'કૃપા કરીને કોડ દાખલ કરો',
  AppStrings.invalidCode: 'અમાન્ય કોડ',
  AppStrings.resend: 'ફરી મોકલો',
  AppStrings.reset: 'રીસેટ કરો',
  AppStrings.confirm: 'પુષ્ટિ કરો',
  AppStrings.verify: 'ચકાસો',
  AppStrings.resetPassword: 'પાસવર્ડ\nરીસેટ કરો',
  AppStrings.enterConfirmPassword: "કન્ફર્મ પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterConfirmPassword: "કૃપા કરીને પુષ્ટિ પાસવર્ડ દાખલ કરો",
  AppStrings.passwordDidNotMatch: "પાસવર્ડ મેળ ખાતો નથી",
  AppStrings.enterEmailAddress: "ઇમેઇલ એડ્રેસ દાખલ કરો",
  AppStrings.pleaseEnterEmailAddress: "કૃપા કરીને ઇમેઇલ એડ્રેસ દાખલ કરો",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો",
  AppStrings.enterYourName: "તમારું નામ દાખલ કરો",
  AppStrings.pleaseEnterYourName: "કૃપા કરીને તમારું નામ દાખલ કરો",
  AppStrings.createAccount: "ખાતું બનાવો",
  AppStrings.alreadyAMember: "પહેલેથી જ એક સભ્ય? ",
  AppStrings.register: "નોંધણી કરો",
  AppStrings.personalDetails: "અંગત વિગતો",
};
