import 'package:bombay_chowpati/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.signUp: "साइन अप करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.enterEmailPhoneNumber: "ईमेल/फ़ोन नंबर दर्ज करें",
  AppStrings.pleaseEnterEmailPhoneNumber: "कृपया ईमेल/फ़ोन नंबर दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.passwordMustContain: "पासवर्ड में कम से कम एक लोअरकेस अक्षर, अपरकेस अक्षर, संख्या और विशेष अक्षर न्यूनतम लंबाई 8 होना चाहिए।",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.quantity: "मात्रा",
  AppStrings.enterQuantity: "मात्रा दर्ज करें",
  AppStrings.pleaseEnterQuantity: "कृपया मात्रा दर्ज करें",
  AppStrings.orderDetails: "ऑर्डर का विवरण",
  AppStrings.add: "जोड़ना",
  AppStrings.invalidInputs: "अमान्य इनपुट",
  AppStrings.selectOrCaptureAImage: "इस छवि को चुनें या कैप्चर करें",
  AppStrings.select: "चुनना",
  AppStrings.camera: "कैमरा",
  AppStrings.gallery: "गैलरी",
  AppStrings.remove: "चयन हटाएँं",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' फ़ोल्डर में सफलतापूर्वक डाउनलोड किया गया।",
  AppStrings.downloadFailedPleaseTryAgain: "डाउनलोड विफल, कृपया पुनः प्रयास करें।",
  AppStrings.contact: "संपर्क",
  AppStrings.contactNumber: "संपर्क नंबर",
  AppStrings.enterContactNumber: "संपर्क नंबर दर्ज करें",
  AppStrings.pleaseEnterContactNumber: "कृपया संपर्क नंबर दर्ज करें",
  AppStrings.edit: "संपादन करना",
  AppStrings.cancel: "रद्द करना",
  AppStrings.delete: "मिटाना",
  AppStrings.update: 'अद्यतन',
  AppStrings.newVersionAvailable: 'एक नया संस्करण उपलब्ध है। कृपया इसे अपग्रेड करें।',
  AppStrings.orderDate: 'आर्डर की तारीख',
  AppStrings.welcomePageTitleOne: 'शीर्ष पर चेरी के साथ वेनिला चॉकलेट शहद',
  AppStrings.welcomePageSubtitleOneTwo: 'गर्मी का समय है',
  AppStrings.welcomePageTitleTwo: 'अपने पसंदीदा आइसक्रीम स्वाद का आनंद लें',
  AppStrings.welcomePageTitleThree: 'एक स्वाद जो आपके विशेष दिन के लिए उपयुक्त है',
  AppStrings.welcomePageSubtitleThree: 'आओ और मेरा पीछा करो',
  AppStrings.forgotPassword: 'पासवर्ड भूल गए?',
  AppStrings.or: 'या',
  AppStrings.enterYourPhoneNumber: 'अपना फोन नंबर दर्ज करे',
  AppStrings.pleaseEnterYourPhoneNumber: 'कृपया अपना फोन नंबर दर्ज करें',
  AppStrings.pleaseEnterYourEmailAddress: 'कृपया अपना ईमेल एड्रेस इंटर करें',
  AppStrings.invalidPhoneNumber: 'अवैध फोन नंबर',
  AppStrings.invalidEmailAddress: 'अमान्य ईमेल एड्रेस',
  AppStrings.weWillSendYouAOTPToSetOrResetYourNewPassword: 'हम आपको आपका नया पासवर्ड सेट या रीसेट करने के लिए एक OTP भेजेंगे',
  AppStrings.sendCode: 'कोड भेजो',
  AppStrings.pleaseEnterCode: 'कृपया कोड दर्ज करें',
  AppStrings.invalidCode: 'अवैध कोड',
  AppStrings.resend: 'पुन: भेजें',
  AppStrings.reset: 'रीसेट',
  AppStrings.confirm: 'पुष्टि करना',
  AppStrings.verify: 'सत्यापित करें',
  AppStrings.resetPassword: 'पासवर्ड\nरीसेट',
  AppStrings.enterConfirmPassword: "पुष्टि पासवर्ड दर्ज करें",
  AppStrings.pleaseEnterConfirmPassword: "कृपया पुष्टि पासवर्ड दर्ज करें",
  AppStrings.passwordDidNotMatch: "पासवर्ड मेल नहीं खाया",
  AppStrings.enterEmailAddress: "ईमेल एड्रेस दर्ज करें",
  AppStrings.pleaseEnterEmailAddress: "कृपया ईमेल एड्रेस दर्ज करें",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें",
  AppStrings.enterYourName: "अपना नाम दर्ज करें",
  AppStrings.pleaseEnterYourName: "कृपया अपना नाम दर्ज करें",
  AppStrings.createAccount: "खाता बनाएं",
  AppStrings.alreadyAMember: "क्या पहले से ही सदस्य हैं? ",
  AppStrings.register: "पंजीकरण करवाना",
  AppStrings.personalDetails: "व्यक्तिगत विवरण",
  AppStrings.changePassword: "पासवर्ड बदलें",
  AppStrings.enterYourOldPassword: "अपना पुराना पासवर्ड डालें",
  AppStrings.pleaseEnterYourOldPassword: "कृपया अपना पुराना पासवर्ड दर्ज करें",
  AppStrings.enterNewPassword: "नया पासवर्ड दर्ज करें",
  AppStrings.pleaseEnterNewPassword: "कृपया नया पासवर्ड दर्ज करें",
  AppStrings.confirmNewPassword: "नए पासवर्ड की पुष्टि करें",
  AppStrings.pleaseConfirmNewPassword: "कृपया नये पासवर्ड की पुष्टि करें",
  AppStrings.oldAndNewPasswordMustBeDifferent: "पुराना और नया पासवर्ड अलग-अलग होना चाहिए",
  AppStrings.change: "परिवर्तन",
  AppStrings.deleteAccount: "खाता हटा दो",
  AppStrings.editProfile: "प्रोफ़ाइल संपादित करें",
  AppStrings.cart: "कार्ट",
  AppStrings.orderHistory: "पुराने ऑर्डर",
  AppStrings.privacyPolicy: "गोपनीयता नीति",
  AppStrings.termsAndConditions: "नियम एवं शर्तें",
  AppStrings.iAgreeWithTermsAndConditions: "मैं नियम एवं शर्तों से सहमत हूं",
  AppStrings.pleaseAcceptTermsAndConditions: "कृपया नियम एवं शर्तें स्वीकार करें",
  AppStrings.favourite: "पसंदीदा",
  AppStrings.selectSize: "आकार चुना",
  AppStrings.yesDelete: "हाँ, हटाएँ",
  AppStrings.areYouSureYouWantToLogout: "क्या आप लॉग आउट करना चाहते हैं?",
  AppStrings.areYouSureYouWantToDeleteAccount: "क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं? इसके बाद आप अपना अकाउंट डेटा खो देंगे.",
  AppStrings.search: "खोज",
  AppStrings.mrp: "MRP: ",
  AppStrings.totalAmount: "कुल राशि: ",
  AppStrings.productAdded: "उत्पाद जोड़ा गया",
  AppStrings.productsAdded: "उत्पाद जोड़े गए",
  AppStrings.viewCart: "टोकरी देखें",
  AppStrings.viewProducts: "उत्पाद देखें",
  AppStrings.totalPayableAmount: "कुल देय राशि: ",
  AppStrings.offerOfferOffer: "प्रस्ताव! प्रस्ताव! प्रस्ताव! प्रत्येक उत्पाद पर 10 लीटर से अधिक की खरीद पर थोक मूल्य पर विचार किया जा रहा है।",
  AppStrings.addNewAddress: "नया पता जोड़ें",
  AppStrings.placeOrder: "आदेश देना",
  AppStrings.addresses: "पतों",
  AppStrings.selectAddressToPlaceOrder: "ऑर्डर देने के लिए पता चुनें",
  AppStrings.enterAddress: "पता दर्ज करें",
  AppStrings.pleaseEnterAddress: "कृपया पता दर्ज करें",
  AppStrings.selectPinCode: "पिन-कोड चुनें",
  AppStrings.pleaseSelectPinCode: "कृपया पिन-कोड चुनें",
  AppStrings.editAddress: "पता संपादित करें",
  AppStrings.changeAnAddressDetails: "पते का विवरण बदलें",
  AppStrings.areYouSureYouWantToDeleteSelectedAddress: "क्या आप वाकई चयनित पता हटाना चाहते हैं?",
  AppStrings.status: "स्थिति",
  AppStrings.pending: "लंबित",
  AppStrings.completed: "पूरा",
  AppStrings.cancelled: "रद्द",
  AppStrings.areYouSureYouWantToPlaceOrderWithSelectedItems: "क्या आप वाकई चयनित वस्तुओं के साथ ऑर्डर देना चाहते हैं?",
  AppStrings.pleaseSelectOrAddAddress: "कृपया पता चुनें या जोड़ें",
  AppStrings.addressNotAddedYet: "पता अभी तक नहीं जोड़ा गया",
  AppStrings.defaultAddressCantBeDeleted: "बुनियादी पता हटाया नहीं जा सकता। या नया पता जोड़ें और बुनियादी के रूप में सेट करें, फिर अपनी इच्छानुसार हटा दे।",
  AppStrings.size: "माप: ",
  AppStrings.pleaseEnterValidPhoneNumber: "कृपया एक वैध नंबर डालें",
  AppStrings.enterPhoneNumberOptional: "फ़ोन नंबर दर्ज करें (वैकल्पिक)",
  AppStrings.refresh: "पुनश्चर्या",
  AppStrings.total: "कुल",
  AppStrings.price: "कीमत",
  AppStrings.pleaseAddAtLeast1ItemOf5Liter: "कृपया 5 लीटर माप का कम से कम 1 आइटम जोड़ें या 750 ML माप के कम से कम 7 आइटम जोड़ें।",
  AppStrings.somethingWentWrongPleaseReVerifyPhoneNumber: "कुछ गलत हो गया, कृपया फ़ोन नंबर पुनः सत्यापित करें।",
  AppStrings.phoneNumberIsInvalid: "फ़ोन नंबर अमान्य है।",
  AppStrings.otpVerifiedSuccessfully: "OTP सफलतापूर्वक सत्यापित हो गया।",
};
