import 'package:bombay_chowpati/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.signUp: "साइन अप करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.enterEmailPhoneNumber: "ईमेल/फ़ोन नंबर दर्ज करें",
  AppStrings.pleaseEnterEmailPhoneNumber: "कृपया ईमेल/फ़ोन नंबर दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.passwordMustContain: "पासवर्ड में कम से कम एक लोअरकेस अक्षर, अपरकेस अक्षर, संख्या और विशेष अक्षर न्यूनतम लंबाई 8 होना चाहिए।",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.quantity: "मात्रा",
  AppStrings.enterQuantity: "मात्रा दर्ज करें",
  AppStrings.pleaseEnterQuantity: "कृपया मात्रा दर्ज करें",
  AppStrings.orderDetails: "ऑर्डर का विवरण",
  AppStrings.add: "जोड़ना",
  AppStrings.invalidInputs: "अमान्य इनपुट",
  AppStrings.selectOrCaptureAImage: "इस छवि को चुनें या कैप्चर करें",
  AppStrings.select: "चुनना",
  AppStrings.camera: "कैमरा",
  AppStrings.gallery: "गैलरी",
  AppStrings.remove: "चयन हटाएँं",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' फ़ोल्डर में सफलतापूर्वक डाउनलोड किया गया।",
  AppStrings.downloadFailedPleaseTryAgain: "डाउनलोड विफल, कृपया पुनः प्रयास करें।",
  AppStrings.contact: "संपर्क",
  AppStrings.contactNumber: "संपर्क नंबर",
  AppStrings.enterContactNumber: "संपर्क नंबर दर्ज करें",
  AppStrings.pleaseEnterContactNumber: "कृपया संपर्क नंबर दर्ज करें",
  AppStrings.edit: "संपादन करना",
  AppStrings.cancel: "रद्द करना",
  AppStrings.delete: "मिटाना",
  AppStrings.update: 'अद्यतन',
  AppStrings.newVersionAvailable: 'एक नया संस्करण उपलब्ध है। कृपया इसे अपग्रेड करें।',
  AppStrings.orderDate: 'आर्डर की तारीख',
  AppStrings.welcomePageTitleOne: 'शीर्ष पर चेरी के साथ वेनिला चॉकलेट शहद',
  AppStrings.welcomePageSubtitleOneTwo: 'गर्मी का समय है',
  AppStrings.welcomePageTitleTwo: 'अपने पसंदीदा आइसक्रीम स्वाद का आनंद लें',
  AppStrings.welcomePageTitleThree: 'एक स्वाद जो आपके विशेष दिन के लिए उपयुक्त है',
  AppStrings.welcomePageSubtitleThree: 'आओ और मेरा पीछा करो',
  AppStrings.forgotPassword: 'पासवर्ड भूल गए?',
  AppStrings.or: 'या',
  AppStrings.enterYourEmailAddress: 'अपना ईमेल एड्रेस दर्ज करें',
  AppStrings.pleaseEnterYourEmailAddress: 'कृपया अपना ईमेल एड्रेस इंटर करें',
  AppStrings.invalidEmailAddress: 'अमान्य ईमेल एड्रेस',
  AppStrings.weWillSendYouAMessageToSetOrResetYourNewPassword: 'हम आपको आपका नया पासवर्ड सेट या रीसेट करने के लिए एक संदेश भेजेंगे',
  AppStrings.sendCode: 'कोड भेजो',
  AppStrings.pleaseEnterCode: 'कृपया कोड दर्ज करें',
  AppStrings.invalidCode: 'अवैध कोड',
  AppStrings.resend: 'पुन: भेजें',
  AppStrings.reset: 'रीसेट',
  AppStrings.confirm: 'पुष्टि करना',
  AppStrings.verify: 'सत्यापित करें',
  AppStrings.resetPassword: 'पासवर्ड\nरीसेट',
  AppStrings.enterConfirmPassword: "पुष्टि पासवर्ड दर्ज करें",
  AppStrings.pleaseEnterConfirmPassword: "कृपया पुष्टि पासवर्ड दर्ज करें",
  AppStrings.passwordDidNotMatch: "पासवर्ड मेल नहीं खाया",
  AppStrings.enterEmailAddress: "ईमेल एड्रेस दर्ज करें",
  AppStrings.pleaseEnterEmailAddress: "कृपया ईमेल एड्रेस दर्ज करें",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें",
  AppStrings.enterYourName: "अपना नाम दर्ज करें",
  AppStrings.pleaseEnterYourName: "कृपया अपना नाम दर्ज करें",
  AppStrings.createAccount: "खाता बनाएं",
  AppStrings.alreadyAMember: "क्या पहले से ही सदस्य हैं? ",
  AppStrings.register: "पंजीकरण करवाना",
  AppStrings.personalDetails: "व्यक्तिगत विवरण",
  AppStrings.changePassword: "पासवर्ड बदलें",
  AppStrings.enterYourOldPassword: "अपना पुराना पासवर्ड डालें",
  AppStrings.pleaseEnterYourOldPassword: "कृपया अपना पुराना पासवर्ड दर्ज करें",
  AppStrings.enterNewPassword: "नया पासवर्ड दर्ज करें",
  AppStrings.pleaseEnterNewPassword: "कृपया नया पासवर्ड दर्ज करें",
  AppStrings.confirmNewPassword: "नए पासवर्ड की पुष्टि करें",
  AppStrings.pleaseConfirmNewPassword: "कृपया नये पासवर्ड की पुष्टि करें",
  AppStrings.oldAndNewPasswordMustBeDifferent: "पुराना और नया पासवर्ड अलग-अलग होना चाहिए",
  AppStrings.change: "परिवर्तन",
  AppStrings.deleteAccount: "खाता हटा दो",
  AppStrings.editProfile: "प्रोफ़ाइल संपादित करें",
  AppStrings.cart: "कार्ट",
  AppStrings.orderHistory: "पुराने ऑर्डर",
};
