import 'package:bombay_chowpati/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.signUp: "साइन अप करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.enterEmailPhoneNumber: "ईमेल/फ़ोन नंबर दर्ज करें",
  AppStrings.pleaseEnterEmailPhoneNumber: "कृपया ईमेल/फ़ोन नंबर दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.quantity: "मात्रा",
  AppStrings.enterQuantity: "मात्रा दर्ज करें",
  AppStrings.pleaseEnterQuantity: "कृपया मात्रा दर्ज करें",
  AppStrings.orderDetails: "ऑर्डर का विवरण",
  AppStrings.add: "जोड़ना",
  AppStrings.invalidInputs: "अमान्य इनपुट",
  AppStrings.selectOrCaptureAImage: "इस छवि को चुनें या कैप्चर करें",
  AppStrings.select: "चुनना",
  AppStrings.camera: "कैमरा",
  AppStrings.gallery: "गैलरी",
  AppStrings.remove: "चयन हटाएँं",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' फ़ोल्डर में सफलतापूर्वक डाउनलोड किया गया।",
  AppStrings.downloadFailedPleaseTryAgain: "डाउनलोड विफल, कृपया पुनः प्रयास करें।",
  AppStrings.contact: "संपर्क",
  AppStrings.contactNumber: "संपर्क नंबर",
  AppStrings.enterContactNumber: "संपर्क नंबर दर्ज करें",
  AppStrings.pleaseEnterContactNumber: "कृपया संपर्क नंबर दर्ज करें",
  AppStrings.edit: "संपादन करना",
  AppStrings.cancel: "रद्द करना",
  AppStrings.delete: "मिटाना",
  AppStrings.update: 'अद्यतन',
  AppStrings.newVersionAvailable: 'एक नया संस्करण उपलब्ध है। कृपया इसे अपग्रेड करें।',
  AppStrings.orderDate: 'आर्डर की तारीख',
  AppStrings.welcomePageTitleOne: 'शीर्ष पर चेरी के साथ वेनिला चॉकलेट शहद',
  AppStrings.welcomePageSubtitleOneTwo: 'गर्मी का समय है',
  AppStrings.welcomePageTitleTwo: 'अपने पसंदीदा आइसक्रीम स्वाद का आनंद लें',
  AppStrings.welcomePageTitleThree: 'एक स्वाद जो आपके विशेष दिन के लिए उपयुक्त है',
  AppStrings.welcomePageSubtitleThree: 'आओ और मेरा पीछा करो',
  AppStrings.forgotPassword: 'पासवर्ड भूल गए?',
  AppStrings.or: 'या',
  AppStrings.enterYourEmailAddress: 'अपना ईमेल एड्रेस दर्ज करें',
  AppStrings.pleaseEnterYourEmailAddress: 'कृपया अपना ईमेल एड्रेस इंटर करें',
  AppStrings.invalidEmailAddress: 'अमान्य ईमेल एड्रेस',
  AppStrings.weWillSendYouAMessageToSetOrResetYourNewPassword: 'हम आपको आपका नया पासवर्ड सेट या रीसेट करने के लिए एक संदेश भेजेंगे',
  AppStrings.sendCode: 'कोड भेजो',
  AppStrings.pleaseEnterCode: 'कृपया कोड दर्ज करें',
  AppStrings.invalidCode: 'अवैध कोड',
  AppStrings.resend: 'पुन: भेजें',
  AppStrings.reset: 'रीसेट',
  AppStrings.confirm: 'पुष्टि करना',
};
